spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chatDB
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
auth:
  jwt:
    secretKey: 7JWI64WV7ZWY64uk7KCQ7J6Q7YSM7JqULg==
    accessExp: 1800
    refreshExp: 50400
    header: Authorization
    prefix: Bearer

logging.level:
  root: info
  #org.hibernate.SQL: debug
